### ISSUE TITLE
Large JS assets won't import?

### ISSUE THREAD

**Issue by fmmich** [jsreport/jsreport-import-export#2]
My organization uses assets and the import/export feature to include third-party Javascript libraries because our servers that run Jsreport prohibit outbound HTTP/HTTPS access for security reasons.  This has worked well until we added Chart.min,js to one of our reports.  

Chart.min.js works correctly within our report as an asset.  It seems that we can export the asset for Chart.min.js from Jsreport Studio of our main source-controlled server, but we can't import the asset into any Jsreport Studio, even into itself.  There is no error message in the dialog; it just won't import.  

To replicate this issue yourself:

1. Download https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js to a local copy.
2. In Jsreport Studio, create an asset for Chart.min.js.  From the dialog, upload the local copy of Chart.min.js.
3. Export just this asset using the Export menu command from Jsreport Studio to create an export.zip file.
4. Delete the asset from Jsreport Studio.
5. Import the export.zip file that was created using the Import menu command from Jsreport Studio.

In debugging this, it appears that a promise is being resolved before the file stream is fully read, but that's as far as I could get.  I replicated this issue with Jsreport 1.7.  Please note that using Chart.min.js as a link to the CDN with Jsreport is not a solution with our organization.  

In advance, your assistance is greatly appreciated.

**Comment by pofider** [comment]
Excellent problem description! Thank you, we will look into it.

**Comment by pofider** [comment]
It looks [the library we use for unzip](https://github.com/glebdmitriew/node-unzip-2) wrongly emits the stream close before the entries' stream are fully drained. I tried to check the source of the problem in its source but I'm not very good in streams so I failed.

Instead I did commit the workaround, that should fix the problem using counter.

I'll do some more thinking here and write tests, but you should be able to patch your environment already with this commit
https://github.com/jsreport/jsreport-import-export/commit/7f95a8cb58d6f0d361ef0623e6a55dd10a550ce1

**Comment by fmmich** [comment]
I verified that your workaround corrects the ability to import the large JS asset.  Thank you for your prompt assistance.  I'll leave this ticket open for @pofider to close.

**Comment by pofider** [comment]
Yes great, thank you for the verification.

**Comment by pofider** [comment]
Fix released in jsreport-import-export@0.4.1
jsreport gets this in its next release
