### ISSUE TITLE
Feature Request: Export by tag

### ISSUE THREAD

**Issue by fmmich** [jsreport/jsreport-import-export#3]
Our organization is using the recent tag feature to categorize our entities, and it has been one of the best organizational features added to Jsreport Studio.  We have several entities under the same tag to represent a group of reports.  Some entities will have multiple tags.  Our organization also uses the import/export feature heavily to deploy our reports.  Our reports are built using a main source-controlled server, and we deploy the reports categorically, which is where tags make sense to use.  

I'd like to request a feature to the export dialog within Jsreport Studio to export entities by tag.  For example, I have a group of Accounting reports, which have templates, scripts, assets, and images.  All of the entities in our group of Accounting reports have the tag "Accounting".  I'd like to export all entities with that tag.  Currently, I have to determine the Accounting tag's color and attempt to match the entities individually in the export dialog via checking and unchecking checkboxes.

If the "Filter entities by tag" UI in the upper left corner of Jsreport Studio can be added to the export dialog and used to filter the entities to export, we will eliminate any chance of missing an entity with that tag.

**Comment by bjrmatos** [comment]
> If the "Filter entities by tag" UI in the upper left corner of Jsreport Studio can be added to the export dialog and used to filter the entities to export, we will eliminate any chance of missing an entity with that tag.

seems good to me and a great use case of tags, so i'm 👍 to support this feature

what do you think @pofider ?

**Comment by pofider** [comment]
Sure, it makes sense. We have more priority things to do, but it looks easy so we should be able to fit it somewhere to the plan.

**Comment by pofider** [comment]
We've recently implemented [folder support](https://jsreport.net/blog/introducing-folders) for jsreport.
This includes also feature to export and import specific folder.
I believe that this will replace tags in most cases and exporting by tags won't be needed.
I am closing for this reason.

We will consider this again if we get further requests for it.
